require 'mustpl/save-load'
require 'mustpl/main'
require 'mustpl/song'
require 'mustpl/songlist'
require 'mustpl/collection'
require 'mustpl/vk'
require 'mustpl/storage-local'
require 'mustpl/storage-vk'
